Пример на датасете 1 000 000 строк: сравним одинаковую операцию в pandas и Polars - groupby + mean.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/synthetic_faers_1m_v3.csv')
df.head(10)

,case_id,receive_date,country,age,age_group,sex,weight_kg,suspect_drug,indication,route,...,concomitant_medications,medical_history,reporter_type,report_type,causality_assessment,alt_u_l,ast_u_l,bilirubin_mg_dl,creatinine_mg_dl,bun_mg_dl
0,E787C9A1FC17D940,2023-04-19,CHN,52,adult,Unknown,NaN,Hematocare,Hypothyroidism,Subcutaneous,...,Aspirin,NaN,Physician,Spontaneous,Probable/Likely,12.0,12.0,0.4,1.0,16.0
1,A29236736650CAB3,2021-10-30,POL,45,adult,Male,110.5,Osteostrong,Bipolar disorder,Intravenous,...,Hydrochlorothiazide,NaN,Consumer,Clinical trial,Probable/Likely,15.0,NaN,0.5,7.1,46.0
2,837A1C25D1B0ED72,2021-09-12,ITA,92,elderly,Female,NaN,Hematocare,COPD,Subcutaneous,...,NaN,Hyperlipidemia; Alcohol use disorder; Chronic ...,Physician,Spontaneous,Possible,340.0,NaN,9.5,0.9,15.0
3,BF1523DD99667C0D,2021-10-03,USA,47,adult,Male,115.0,Vasodilate,Schizophrenia,Ophthalmic,...,NaN,Peripheral vascular disease; Hypothyroidism; P...,Consumer,Spontaneous,Possible,45.0,NaN,1.1,1.2,9.0
4,F470F722F96A2FF7,2021-03-08,GBR,19,adult,Female,94.4,Cardiomax,Rheumatoid arthritis,Intramuscular,...,Pantoprazole; Hydrochlorothiazide,NaN,Pharmacist,Spontaneous,Unlikely,33.0,35.0,0.1,1.1,12.0
5,785B2438894CDCFA,2025-08-05,ESP,89,elderly,Male,111.7,Eyeprotect,Rheumatoid arthritis,Topical,...,Warfarin; Aspirin,Osteoarthritis; Depression,Other health professional,Literature,Possible,27.0,26.0,1.2,NaN,NaN
6,5A0796C50364BAA5,2023-04-29,CAN,58,adult,Unknown,58.1,Immunoshield,Type 2 diabetes,Topical,...,Atorvastatin; Ciprofloxacin,Chronic pain; Hypothyroidism; Heart failure,Lawyer,Spontaneous,Possible,28.0,16.0,1.1,1.2,11.0
7,BEA3CC1D4F66B39B,2022-04-26,NLD,47,adult,Unknown,NaN,Eyeprotect,Anxiety,Intravenous,...,Lisinopril,Hepatitis B,Consumer,Spontaneous,Possible,34.0,NaN,0.9,1.2,19.0
8,A3B710F35B3DBE9E,2022-04-13,BEL,78,elderly,Unknown,NaN,Thyroregul,Schizophrenia,Inhalation,...,Warfarin,Gastroesophageal reflux disease; Occupational ...,Lawyer,Spontaneous,Unlikely,27.0,32.0,0.4,NaN,10.0
9,73BDA39A3B797270,2021-10-29,AUT,9,child,Unknown,46.2,Cardiomax,Infection,Ophthalmic,...,Acetaminophen; Warfarin,Gastroesophageal reflux disease,Lawyer,Spontaneous,Possible,34.0,31.0,0.9,1.2,NaN

In [4]:
import time
import polars as pl

# pandas DataFrame у тебя уже есть: df
pdf = df

# создаем Polars DataFrame
pldf = pl.from_pandas(pdf)

In [5]:
def benchmark_many(func, name, repeats=5):
    times = []

    for _ in range(repeats):
        start = time.perf_counter()
        result = func()
        end = time.perf_counter()
        times.append(end - start)

    avg_time = sum(times) / len(times)

    print(f"{name}")
    print(f"Среднее время: {avg_time:.4f} секунд")
    print(f"Все замеры: {[round(t, 4) for t in times]}")
    print("-" * 50)

    return result

In [6]:
pandas_result_1 = benchmark_many(
    lambda: (
        pdf
        .groupby("seriousness")
        .agg(
            cnt=("case_id", "count"),
            avg_age=("age", "mean"),
            avg_dose=("dose", "mean"),
            avg_time_to_onset=("time_to_onset_days", "mean")
        )
        .sort_values("cnt", ascending=False)
    ),
    "Pandas: groupby seriousness"
)
pandas_result_1

Pandas: groupby seriousness
Среднее время: 0.1798 секунд
Все замеры: [0.1843, 0.1727, 0.1778, 0.1875, 0.1767]
--------------------------------------------------

,cnt,avg_age,avg_dose,avg_time_to_onset
seriousness,,,,
Non-serious,649378,46.357651,66.087401,100.510649
Hospitalization - initial or prolonged,58805,46.454655,65.045438,100.755140
Disability,58504,46.341430,65.305073,99.875205
Congenital anomaly,58501,46.297927,64.615801,100.644519
Death,58422,46.227774,66.038753,100.022355
Life-threatening,58202,46.166627,65.587059,101.150167
Other medically important condition,58188,46.303035,64.990771,101.409483

In [7]:
polars_result_1 = benchmark_many(
    lambda: (
        pldf
        .group_by("seriousness")
        .agg(
            pl.len().alias("cnt"),
            pl.col("age").mean().alias("avg_age"),
            pl.col("dose").mean().alias("avg_dose"),
            pl.col("time_to_onset_days").mean().alias("avg_time_to_onset")
        )
        .sort("cnt", descending=True)
    ),
    "Polars: group_by seriousness"
)
polars_result_1

Polars: group_by seriousness
Среднее время: 0.0409 секунд
Все замеры: [0.0443, 0.0408, 0.0498, 0.0341, 0.0354]
--------------------------------------------------

shape: (7, 5)
┌─────────────────────────────────┬────────┬───────────┬───────────┬───────────────────┐
│ seriousness                     ┆ cnt    ┆ avg_age   ┆ avg_dose  ┆ avg_time_to_onset │
│ ---                             ┆ ---    ┆ ---       ┆ ---       ┆ ---               │
│ str                             ┆ u32    ┆ f64       ┆ f64       ┆ f64               │
╞═════════════════════════════════╪════════╪═══════════╪═══════════╪═══════════════════╡
│ Non-serious                     ┆ 649378 ┆ 46.357651 ┆ 66.087401 ┆ 100.510649        │
│ Hospitalization - initial or p… ┆ 58805  ┆ 46.454655 ┆ 65.045438 ┆ 100.75514         │
│ Disability                      ┆ 58504  ┆ 46.34143  ┆ 65.305073 ┆ 99.875205         │
│ Congenital anomaly              ┆ 58501  ┆ 46.297927 ┆ 64.615801 ┆ 100.644519        │
│ Death                           ┆ 58422  ┆ 46.227774 ┆ 66.038753 ┆ 100.022355        │
│ Life-threatening                ┆ 58202  ┆ 46.166627 ┆ 65.587059 ┆ 101.150167        │
│ Other medically important cond… ┆ 58188  ┆ 46.303035 ┆ 64.990771 ┆ 101.409483        │
└─────────────────────────────────┴────────┴───────────┴───────────┴───────────────────┘

In [8]:
pandas_result_2 = benchmark_many(
    lambda: (
        pdf[pdf["seriousness"] == "Serious"]
        .groupby("suspect_drug")
        .agg(
            cnt=("case_id", "count"),
            avg_age=("age", "mean"),
            avg_bilirubin=("bilirubin_mg_dl", "mean"),
            avg_creatinine=("creatinine_mg_dl", "mean")
        )
        .sort_values("cnt", ascending=False)
        .head(20)
    ),
    "Pandas: filter Serious + groupby suspect_drug"
)
pandas_result_2

Pandas: filter Serious + groupby suspect_drug
Среднее время: 0.0779 секунд
Все замеры: [0.0786, 0.0795, 0.0777, 0.078, 0.0759]
--------------------------------------------------

Empty DataFrame
Columns: [cnt, avg_age, avg_bilirubin, avg_creatinine]
Index: []

In [9]:
polars_result_2 = benchmark_many(
    lambda: (
        pldf
        .filter(pl.col("seriousness") == "Serious")
        .group_by("suspect_drug")
        .agg(
            pl.len().alias("cnt"),
            pl.col("age").mean().alias("avg_age"),
            pl.col("bilirubin_mg_dl").mean().alias("avg_bilirubin"),
            pl.col("creatinine_mg_dl").mean().alias("avg_creatinine")
        )
        .sort("cnt", descending=True)
        .head(20)
    ),
    "Polars: filter Serious + group_by suspect_drug"
)
polars_result_2

Polars: filter Serious + group_by suspect_drug
Среднее время: 0.0037 секунд
Все замеры: [0.0068, 0.003, 0.0028, 0.0028, 0.0029]
--------------------------------------------------

shape: (0, 5)
┌──────────────┬─────┬─────────┬───────────────┬────────────────┐
│ suspect_drug ┆ cnt ┆ avg_age ┆ avg_bilirubin ┆ avg_creatinine │
│ ---          ┆ --- ┆ ---     ┆ ---           ┆ ---            │
│ str          ┆ u32 ┆ f64     ┆ f64           ┆ f64            │
╞══════════════╪═════╪═════════╪═══════════════╪════════════════╡
└──────────────┴─────┴─────────┴───────────────┴────────────────┘

In [10]:
def benchmark_many(func, name, repeats=5):
    times = []

    for _ in range(repeats):
        start = time.perf_counter()
        result = func()
        end = time.perf_counter()
        times.append(end - start)

    avg_time = sum(times) / len(times)

    print(f"{name}")
    print(f"Среднее время: {avg_time:.4f} секунд")
    print(f"Все замеры: {[round(t, 4) for t in times]}")
    print("-" * 60)

    return result

In [11]:
pandas_complex_1 = benchmark_many(
    lambda: (
        pdf[
            (pdf["seriousness"] == "Serious") &
            (pdf["age"].notna()) &
            (pdf["dose"].notna()) &
            (pdf["creatinine_mg_dl"].notna())
        ]
        .groupby(["suspect_drug", "outcome"])
        .agg(
            cnt=("case_id", "count"),
            avg_age=("age", "mean"),
            median_age=("age", "median"),
            avg_dose=("dose", "mean"),
            max_dose=("dose", "max"),
            avg_creatinine=("creatinine_mg_dl", "mean"),
            avg_bilirubin=("bilirubin_mg_dl", "mean")
        )
        .sort_values("cnt", ascending=False)
        .head(20)
    ),
    "Pandas: complex filter + groupby drug/outcome"
)
pandas_complex_1

Pandas: complex filter + groupby drug/outcome
Среднее время: 0.0861 секунд
Все замеры: [0.087, 0.0856, 0.086, 0.0873, 0.0847]
------------------------------------------------------------

Empty DataFrame
Columns: [cnt, avg_age, median_age, avg_dose, max_dose, avg_creatinine, avg_bilirubin]
Index: []

In [12]:
polars_complex_1 = benchmark_many(
    lambda: (
        pldf
        .filter(
            (pl.col("seriousness") == "Serious") &
            pl.col("age").is_not_null() &
            pl.col("dose").is_not_null() &
            pl.col("creatinine_mg_dl").is_not_null()
        )
        .group_by(["suspect_drug", "outcome"])
        .agg(
            pl.len().alias("cnt"),
            pl.col("age").mean().alias("avg_age"),
            pl.col("age").median().alias("median_age"),
            pl.col("dose").mean().alias("avg_dose"),
            pl.col("dose").max().alias("max_dose"),
            pl.col("creatinine_mg_dl").mean().alias("avg_creatinine"),
            pl.col("bilirubin_mg_dl").mean().alias("avg_bilirubin")
        )
        .sort("cnt", descending=True)
        .head(20)
    ),
    "Polars: complex filter + group_by drug/outcome"
)
polars_complex_1

Polars: complex filter + group_by drug/outcome
Среднее время: 0.0058 секунд
Все замеры: [0.0068, 0.0066, 0.0064, 0.0052, 0.0039]
------------------------------------------------------------

shape: (0, 9)
┌──────────────┬─────────┬─────┬─────────┬───┬──────────┬──────────┬───────────────┬───────────────┐
│ suspect_drug ┆ outcome ┆ cnt ┆ avg_age ┆ … ┆ avg_dose ┆ max_dose ┆ avg_creatinin ┆ avg_bilirubin │
│ ---          ┆ ---     ┆ --- ┆ ---     ┆   ┆ ---      ┆ ---      ┆ e             ┆ ---           │
│ str          ┆ str     ┆ u32 ┆ f64     ┆   ┆ f64      ┆ i64      ┆ ---           ┆ f64           │
│              ┆         ┆     ┆         ┆   ┆          ┆          ┆ f64           ┆               │
╞══════════════╪═════════╪═════╪═════════╪═══╪══════════╪══════════╪═══════════════╪═══════════════╡
└──────────────┴─────────┴─────┴─────────┴───┴──────────┴──────────┴───────────────┴───────────────┘

In [13]:
def pandas_complex_transform():
    temp = pdf.copy()

    temp["age_segment"] = pd.cut(
        temp["age"],
        bins=[0, 30, 45, 60, 75, 120],
        labels=["<30", "30-45", "45-60", "60-75", "75+"],
        right=False
    )

    temp["high_dose_flag"] = temp["dose"] > temp["dose"].median()
    temp["high_creatinine_flag"] = temp["creatinine_mg_dl"] > 1.2

    result = (
        temp
        .groupby(["age_segment", "seriousness", "high_creatinine_flag"], observed=True)
        .agg(
            cnt=("case_id", "count"),
            avg_dose=("dose", "mean"),
            avg_alt=("alt_u_l", "mean"),
            avg_ast=("ast_u_l", "mean"),
            avg_bun=("bun_mg_dl", "mean"),
            serious_rate=("high_dose_flag", "mean")
        )
        .sort_values("cnt", ascending=False)
        .head(30)
    )

    return result


pandas_complex_2 = benchmark_many(
    pandas_complex_transform,
    "Pandas: create features + groupby"
)
pandas_complex_2

Pandas: create features + groupby
Среднее время: 0.7491 секунд
Все замеры: [1.0066, 0.6609, 0.7158, 0.6894, 0.6728]
------------------------------------------------------------

                                                                            cnt  \
age_segment seriousness                            high_creatinine_flag
<30         Non-serious                            False                 174305
45-60       Non-serious                            False                 108836
30-45       Non-serious                            False                 108816
75+         Non-serious                            False                  98943
60-75       Non-serious                            False                  89967
<30         Non-serious                            True                   20571
            Life-threatening                       False                  15712
            Congenital anomaly                     False                  15676
            Hospitalization - initial or prolonged False                  15640
            Death                                  False                  15630
            Disability                             False                  15563
            Other medically important condition    False                  15514
45-60       Non-serious                            True                   12913
30-45       Non-serious                            True                   12703
75+         Non-serious                            True                   11735
60-75       Non-serious                            True                   10589
30-45       Hospitalization - initial or prolonged False                  10029
            Death                                  False                   9922
45-60       Congenital anomaly                     False                   9920
30-45       Life-threatening                       False                   9887
            Other medically important condition    False                   9876
            Disability                             False                   9848
45-60       Hospitalization - initial or prolonged False                   9836
            Death                                  False                   9830
30-45       Congenital anomaly                     False                   9818
45-60       Disability                             False                   9808
            Other medically important condition    False                   9673
            Life-threatening                       False                   9648
75+         Disability                             False                   8932
            Hospitalization - initial or prolonged False                   8925

                                                                          avg_dose  \
age_segment seriousness                            high_creatinine_flag
<30         Non-serious                            False                 65.954287
45-60       Non-serious                            False                 66.358264
30-45       Non-serious                            False                 65.664222
75+         Non-serious                            False                 65.452220
60-75       Non-serious                            False                 66.156368
<30         Non-serious                            True                  68.138447
            Life-threatening                       False                 64.270303
            Congenital anomaly                     False                 66.235009
            Hospitalization - initial or prolonged False                 64.152941
            Death                                  False                 64.874344
            Disability                             False                 64.954636
            Other medically important condition    False                 63.098105
45-60       Non-serious                            True                  66.575312
30-45       Non-serious                            True                  67.779816
75+         Non-serious                            True                  69.372987
60-75       Non-serious                            True                  64.941449
30-45       Hospitalization - initial or prolonged False                 68.057433
            Death                                  False                 67.185043
45-60       Congenital anomaly                     False                 66.491028
30-45       Life-threatening                       False                 68.607768
            Other medically important condition    False                 65.042224
            Disability                             False                 67.263404
45-60       Hospitalization - initial or prolonged False                 62.347397
            Death                                  False                 67.333876
30-45       Congenital anomaly                     False                 61.426054
45-60       Disability                             False                 63.029364
            Other medically important condition    False                 67.206141
            Life-threatening                       False                 62.551928
75+         Disability                             False                 62.302060
            Hospitalization - initial or prolonged False                 66.870588

                                                                           avg_alt  \
age_segment seriousness                            high_creatinine_flag
<30         Non-serious                            False                 60.814814
45-60       Non-serious                            False                 60.781092
30-45       Non-serious                            False                 60.304331
75+         Non-serious                            False                 61.202102
60-75       Non-serious                            False                 60.666390
<30         Non-serious                            True                  43.705939
            Life-threatening                       False                 60.980183
            Congenital anomaly                     False                 58.817640
            Hospitalization - initial or prolonged False                 60.929090
            Death                                  False                 60.083162
            Disability                             False                 60.628625
            Other medically important condition    False                 62.017986
45-60       Non-serious                            True                  43.103745
30-45       Non-serious                            True                  43.979282
75+         Non-serious                            True                  44.278119
60-75       Non-serious                            True                  42.177312
30-45       Hospitalization - initial or prolonged False                 59.831349
            Death                                  False                 59.354276
45-60       Congenital anomaly                     False                 57.414895
30-45       Life-threatening                       False                 60.926369
            Other medically important condition    False                 62.044429
            Disability                             False                 58.489600
45-60       Hospitalization - initial or prolonged False                 64.477033
            Death                                  False                 61.976507
30-45       Congenital anomaly                     False                 62.164692
45-60       Disability                             False                 62.289031
            Other medically important condition    False                 61.024945
            Life-threatening                       False                 63.992430
75+         Disability                             False                 61.348976
            Hospitalization - initial or prolonged False                 63.117035

                                                                           avg_ast  \
age_segment seriousness                            high_creatinine_flag
<30         Non-serious                            False                 56.530836
45-60       Non-serious                            False                 56.052958
30-45       Non-serious                            False                 55.683795
75+         Non-serious                            False                 56.721102
60-75       Non-serious                            False                 56.346247
<30         Non-serious                            True                  39.322463
            Life-threatening                       False                 56.276224
            Congenital anomaly                     False                 56.121145
            Hospitalization - initial or prolonged False                 55.844721
            Death                                  False                 54.579605
            Disability                             False                 55.553361
            Other medically important condition    False                 55.271027
45-60       Non-serious                            True                  40.681050
30-45       Non-serious                            True                  38.870405
75+         Non-serious                            True                  38.609701
60-75       Non-serious                            True                  39.497049
30-45       Hospitalization - initial or prolonged False                 56.986323
            Death                                  False                 54.897709
45-60       Congenital anomaly                     False                 55.380353
30-45       Life-threatening                       False                 55.258489
            Other medically important condition    False                 55.591105
            Disability                             False                 53.717009
45-60       Hospitalization - initial or prolonged False                 59.939287
            Death                                  False                 56.835390
30-45       Congenital anomaly                     False                 56.692600
45-60       Disability                             False                 57.175962
            Other medically important condition    False                 59.137146
            Life-threatening                       False                 56.771539
75+         Disability                             False                 57.727300
            Hospitalization - initial or prolonged False                 58.432776

                                                                           avg_bun  \
age_segment seriousness                            high_creatinine_flag
<30         Non-serious                            False                 14.476849
45-60       Non-serious                            False                 14.529606
30-45       Non-serious                            False                 14.547164
75+         Non-serious                            False                 14.458855
60-75       Non-serious                            False                 14.501724
<30         Non-serious                            True                  39.674289
            Life-threatening                       False                 14.392863
            Congenital anomaly                     False                 14.350795
            Hospitalization - initial or prolonged False                 14.452347
            Death                                  False                 14.574415
            Disability                             False                 14.475410
            Other medically important condition    False                 14.543366
45-60       Non-serious                            True                  39.765362
30-45       Non-serious                            True                  39.800294
75+         Non-serious                            True                  39.336278
60-75       Non-serious                            True                  39.217589
30-45       Hospitalization - initial or prolonged False                 14.547041
            Death                                  False                 14.415883
45-60       Congenital anomaly                     False                 14.633822
30-45       Life-threatening                       False                 14.485926
            Other medically important condition    False                 14.530667
            Disability                             False                 14.659219
45-60       Hospitalization - initial or prolonged False                 14.557954
            Death                                  False                 14.581976
30-45       Congenital anomaly                     False                 14.530453
45-60       Disability                             False                 14.557145
            Other medically important condition    False                 14.417543
            Life-threatening                       False                 14.670642
75+         Disability                             False                 14.372652
            Hospitalization - initial or prolonged False                 14.443657

                                                                         serious_rate
age_segment seriousness                            high_creatinine_flag
<30         Non-serious                            False                     0.336141
45-60       Non-serious                            False                     0.336598
30-45       Non-serious                            False                     0.339454
75+         Non-serious                            False                     0.337053
60-75       Non-serious                            False                     0.339224
<30         Non-serious                            True                      0.343104
            Life-threatening                       False                     0.341459
            Congenital anomaly                     False                     0.340967
            Hospitalization - initial or prolonged False                     0.334719
            Death                                  False                     0.339923
            Disability                             False                     0.341258
            Other medically important condition    False                     0.334343
45-60       Non-serious                            True                      0.333153
30-45       Non-serious                            True                      0.344013
75+         Non-serious                            True                      0.339327
60-75       Non-serious                            True                      0.338181
30-45       Hospitalization - initial or prolonged False                     0.338020
            Death                                  False                     0.334610
45-60       Congenital anomaly                     False                     0.339516
30-45       Life-threatening                       False                     0.347426
            Other medically important condition    False                     0.341333
            Disability                             False                     0.341897
45-60       Hospitalization - initial or prolonged False                     0.330622
            Death                                  False                     0.336419
30-45       Congenital anomaly                     False                     0.326950
45-60       Disability                             False                     0.330954
            Other medically important condition    False                     0.345188
            Life-threatening                       False                     0.329291
75+         Disability                             False                     0.344156
            Hospitalization - initial or prolonged False                     0.344314

In [14]:
def polars_complex_transform():
    dose_median = pldf.select(pl.col("dose").median()).item()

    result = (
        pldf
        .with_columns(
            pl.when(pl.col("age") < 30).then(pl.lit("<30"))
              .when(pl.col("age") < 45).then(pl.lit("30-45"))
              .when(pl.col("age") < 60).then(pl.lit("45-60"))
              .when(pl.col("age") < 75).then(pl.lit("60-75"))
              .otherwise(pl.lit("75+"))
              .alias("age_segment"),

            (pl.col("dose") > dose_median).alias("high_dose_flag"),
            (pl.col("creatinine_mg_dl") > 1.2).alias("high_creatinine_flag")
        )
        .group_by(["age_segment", "seriousness", "high_creatinine_flag"])
        .agg(
            pl.len().alias("cnt"),
            pl.col("dose").mean().alias("avg_dose"),
            pl.col("alt_u_l").mean().alias("avg_alt"),
            pl.col("ast_u_l").mean().alias("avg_ast"),
            pl.col("bun_mg_dl").mean().alias("avg_bun"),
            pl.col("high_dose_flag").mean().alias("high_dose_rate")
        )
        .sort("cnt", descending=True)
        .head(30)
    )

    return result


polars_complex_2 = benchmark_many(
    polars_complex_transform,
    "Polars: create features + group_by"
)
polars_complex_2

Polars: create features + group_by
Среднее время: 0.1874 секунд
Все замеры: [0.2506, 0.1985, 0.1767, 0.1611, 0.1502]
------------------------------------------------------------

shape: (30, 9)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ age_segmen ┆ seriousnes ┆ high_crea ┆ cnt    ┆ … ┆ avg_alt   ┆ avg_ast   ┆ avg_bun   ┆ high_dose │
│ t          ┆ s          ┆ tinine_fl ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ _rate     │
│ ---        ┆ ---        ┆ ag        ┆ u32    ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│ str        ┆ str        ┆ ---       ┆        ┆   ┆           ┆           ┆           ┆ f64       │
│            ┆            ┆ bool      ┆        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ <30        ┆ Non-seriou ┆ false     ┆ 125825 ┆ … ┆ 61.300504 ┆ 56.852038 ┆ 13.487138 ┆ 0.336563  │
│            ┆ s          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 30-45      ┆ Non-seriou ┆ false     ┆ 78389  ┆ … ┆ 61.060058 ┆ 56.316734 ┆ 13.510445 ┆ 0.339078  │
│            ┆ s          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 45-60      ┆ Non-seriou ┆ false     ┆ 78325  ┆ … ┆ 61.790328 ┆ 56.457537 ┆ 13.507669 ┆ 0.335742  │
│            ┆ s          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 75+        ┆ Non-seriou ┆ false     ┆ 71393  ┆ … ┆ 61.647057 ┆ 57.329681 ┆ 13.502246 ┆ 0.337414  │
│            ┆ s          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 60-75      ┆ Non-seriou ┆ false     ┆ 64647  ┆ … ┆ 60.669207 ┆ 56.670506 ┆ 13.48835  ┆ 0.338948  │
│            ┆ s          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 45-60      ┆ Hospitaliz ┆ false     ┆ 7095   ┆ … ┆ 64.254858 ┆ 61.18264  ┆ 13.556969 ┆ 0.330374  │
│            ┆ ation -    ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│            ┆ initial or ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│            ┆ p…         ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 30-45      ┆ Other      ┆ false     ┆ 7077   ┆ … ┆ 61.061037 ┆ 56.6031   ┆ 13.486942 ┆ 0.336725  │
│            ┆ medically  ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│            ┆ important  ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│            ┆ cond…      ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 45-60      ┆ Disability ┆ false     ┆ 7062   ┆ … ┆ 63.289381 ┆ 57.920865 ┆ 13.6118   ┆ 0.335599  │
│ 45-60      ┆ Death      ┆ false     ┆ 7054   ┆ … ┆ 63.009655 ┆ 55.614091 ┆ 13.528263 ┆ 0.333995  │
│ 30-45      ┆ Disability ┆ false     ┆ 7048   ┆ … ┆ 59.884492 ┆ 53.978707 ┆ 13.535376 ┆ 0.343076  │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
pandas_complex_3 = benchmark_many(
    lambda: (
        pdf
        .groupby(["country", "sex", "age_group", "suspect_drug", "seriousness"])
        .agg(
            cnt=("case_id", "count"),
            avg_age=("age", "mean"),
            avg_weight=("weight_kg", "mean"),
            avg_dose=("dose", "mean"),
            median_duration=("event_duration_days", "median"),
            avg_alt=("alt_u_l", "mean"),
            avg_ast=("ast_u_l", "mean"),
            avg_bilirubin=("bilirubin_mg_dl", "mean"),
            avg_creatinine=("creatinine_mg_dl", "mean"),
            avg_bun=("bun_mg_dl", "mean")
        )
        .sort_values("cnt", ascending=False)
        .head(50)
    ),
    "Pandas: many keys + many metrics"
)
pandas_complex_3

Pandas: many keys + many metrics
Среднее время: 1.1138 секунд
Все замеры: [0.7244, 0.9157, 1.1937, 1.3795, 1.3555]
------------------------------------------------------------

,,,,,cnt,avg_age,avg_weight,avg_dose,median_duration,avg_alt,avg_ast,avg_bilirubin,avg_creatinine,avg_bun
country,sex,age_group,suspect_drug,seriousness,,,,,,,,,,
ZAF,Male,adult,Psychostabil,Non-serious,216,42.097222,86.265772,79.898148,43.5,46.521472,41.090361,1.100000,1.103247,14.277778
FIN,Male,adult,Pulmofix,Non-serious,215,40.883721,85.719149,65.572093,37.5,50.580838,60.475610,1.255488,1.248428,18.144737
CAN,Male,adult,Pulmofix,Non-serious,215,43.637209,84.850350,44.069767,44.0,62.581699,54.634146,1.261310,1.240361,17.915663
USA,Female,adult,Dermatopin,Non-serious,214,41.747664,84.222794,59.542056,43.0,67.161491,50.796407,1.183436,1.157792,17.218935
TUR,Male,adult,Sleepwell,Non-serious,212,41.613208,84.446259,56.896226,40.0,52.127389,64.438272,1.283544,1.182927,17.617143
GRC,Female,adult,Oncotreat,Non-serious,212,39.127358,83.742336,52.976415,35.5,66.940476,59.030488,1.126582,1.140854,16.768293
NZL,Unknown,adult,Osteostrong,Non-serious,210,40.890476,84.419708,68.095238,41.0,54.622517,50.854430,1.158710,1.352667,17.186335
CHN,Unknown,adult,Gastroease,Non-serious,209,41.559809,84.156250,72.937799,39.0,66.769737,51.808917,1.142308,1.129677,16.603896
BEL,Male,adult,Nephroguard,Non-serious,209,43.717703,86.992908,41.287081,50.0,54.069620,48.616883,1.155844,1.094872,16.278481
FIN,Male,adult,Lipidlow,Non-serious,209,41.110048,84.759864,63.229665,48.0,73.414013,56.270968,1.324051,1.135294,15.980769
NLD,Female,adult,Diabecontrol,Non-serious,209,40.047847,83.937879,65.315789,41.0,65.493333,48.353741,1.276667,1.326452,19.284810
BEL,Male,adult,Osteostrong,Non-serious,208,40.778846,84.536800,93.605769,39.5,63.012903,57.556250,1.452795,1.134591,16.556213
FIN,Unknown,adult,Anticoag-XR,Non-serious,207,40.536232,85.643478,60.062802,38.0,53.730263,61.736486,1.445638,1.210458,18.707006
SWE,Unknown,adult,Hepatosan,Non-serious,207,41.169082,84.854032,110.772947,52.0,64.677019,46.677632,0.986875,1.221019,18.566038
BEL,Unknown,adult,Hepatosan,Non-serious,206,40.655340,84.928226,60.587379,43.0,64.908497,43.542484,1.203165,1.025161,15.119205
MEX,Female,adult,Anticoag-XR,Non-serious,206,41.932039,85.989781,68.160194,37.0,60.800000,55.177215,1.428105,1.239103,18.188679
AUT,Female,adult,Oncotreat,Non-serious,206,41.849515,84.071429,66.441748,46.0,63.961290,52.477707,1.307143,1.190566,16.258065
NLD,Female,adult,Eyeprotect,Non-serious,205,40.751220,84.827407,100.097561,47.0,65.603896,45.280822,1.183871,1.380952,18.469799
CHE,Male,adult,Anticoag-XR,Non-serious,205,41.482927,83.218382,79.878049,36.0,58.202532,56.876623,1.345324,1.155782,15.337349
ISR,Female,adult,Nephroguard,Non-serious,204,41.034314,85.935338,59.450980,41.0,44.390728,47.033557,1.235065,1.137500,16.020000
POL,Male,adult,Neurobalance,Non-serious,204,41.857843,82.709774,60.916667,43.0,55.444444,44.013423,1.130000,1.256329,15.810458
AUT,Female,adult,Eyeprotect,Non-serious,204,42.215686,87.022222,64.147059,42.0,42.873333,36.732394,1.004938,1.415625,19.876623
AUS,Female,adult,Dermafix,Non-serious,204,40.004902,88.225781,67.284314,39.0,48.696552,37.096154,1.084768,1.253061,16.387879
NOR,Female,adult,Hepatosan,Non-serious,204,41.906863,85.976296,90.406863,36.0,57.588235,52.126582,1.180795,1.264029,17.120253
GBR,Unknown,adult,Anticoag-XR,Non-serious,204,40.171569,86.230075,55.083333,41.5,73.659722,62.326667,1.207643,1.266452,18.187919
CHE,Female,adult,Diabecontrol,Non-serious,204,40.191176,80.908594,69.578431,42.0,76.137255,53.123457,1.331579,1.189262,15.866242
POL,Female,adult,Lipidlow,Non-serious,203,42.344828,85.459524,64.482759,39.5,52.326531,52.992908,1.153061,1.217687,16.787097
BEL,Female,adult,Nephroguard,Non-serious,203,41.024631,81.927419,50.443350,44.0,60.348993,60.765101,1.338194,1.283448,17.341935
ZAF,Female,adult,Psychostabil,Non-serious,203,41.655172,84.042105,68.635468,35.0,72.070968,57.907285,1.472436,1.206173,17.406452
MEX,Female,adult,Hematocare,Non-serious,203,43.024631,83.270455,66.945813,38.0,66.047945,59.337838,1.442038,1.257143,17.761905
FIN,Male,adult,Thyroregul,Non-serious,203,40.788177,84.117037,55.103448,43.0,66.496894,52.061350,1.275168,1.254348,17.506579
FRA,Unknown,adult,Immunoshield,Non-serious,203,40.527094,84.338095,76.778325,33.0,59.616438,64.968153,1.336486,1.216561,16.901316
NOR,Female,adult,Dermafix,Non-serious,203,41.916256,84.530075,81.793103,38.0,57.680000,39.973684,0.989172,1.122297,17.190476
NLD,Female,adult,Glucobalance,Non-serious,203,40.802956,87.332353,56.684729,48.5,69.675000,75.671053,1.350327,1.137500,16.927632
CAN,Female,adult,Osteostrong,Non-serious,202,42.084158,86.324615,65.455446,40.0,74.465409,61.409091,1.335714,1.241060,16.099338
KOR,Female,adult,Thyroregul,Non-serious,202,41.950495,85.051181,67.158416,43.0,53.734694,37.618421,0.951299,1.300000,16.000000
NOR,Unknown,adult,Thyroregul,Non-serious,202,41.836634,83.269630,61.079208,53.0,69.496774,63.900000,1.544375,1.265132,15.801325
SWE,Unknown,adult,Cardiomax,Non-serious,202,41.386139,84.673228,51.767327,47.0,57.596026,56.471429,1.517089,1.236486,15.816456
RUS,Female,adult,Lipidlow,Non-serious,202,42.202970,85.471429,66.678218,46.5,50.530201,48.903448,1.011268,1.379592,17.806667
PRT,Male,adult,Infectoban,Non-serious,202,42.113861,85.489474,76.306931,37.0,56.200000,52.335570,1.116000,1.214094,15.670968
MEX,Male,adult,Psychostabil,Non-serious,202,41.861386,83.741007,83.995050,42.0,47.243056,52.675862,1.076027,1.211111,17.884615
JPN,Male,adult,Psychostabil,Non-serious,202,41.257426,85.129851,32.846535,30.0,43.140940,45.184932,0.718571,1.214286,17.490066
BEL,Female,adult,Sleepwell,Non-serious,201,40.054726,85.279286,68.532338,34.5,74.077922,60.467105,1.294595,1.245638,18.836735
GRC,Unknown,adult,Glucobalance,Non-serious,201,41.761194,84.568033,59.850746,37.0,62.381579,56.360544,1.394631,1.248718,17.629870
TUR,Female,adult,Vasodilate,Non-serious,201,41.651741,85.921705,83.154229,37.0,55.068750,40.463087,0.927333,1.173154,16.993243
FRA,Female,adult,Hepatosan,Non-serious,201,42.761194,87.588806,88.199005,43.0,60.068966,44.452055,1.363699,1.040132,14.750000
GBR,Unknown,adult,Pulmofix,Non-serious,201,42.442786,82.408264,72.462687,46.0,76.262500,62.441718,1.373418,1.263514,18.666667
AUT,Unknown,adult,Eyeprotect,Non-serious,201,40.044776,87.630435,53.343284,41.0,52.298137,45.714286,1.031293,1.200680,15.870748
ITA,Unknown,adult,Vasodilate,Non-serious,201,41.333333,86.526154,53.701493,45.0,78.601307,74.750000,1.543421,1.062092,16.019355
AUT,Female,adult,Arthrorelief,Non-serious,201,41.084577,84.393478,80.119403,39.0,60.051948,55.363057,1.073154,1.314194,19.463087

In [16]:
polars_complex_3 = benchmark_many(
    lambda: (
        pldf
        .group_by(["country", "sex", "age_group", "suspect_drug", "seriousness"])
        .agg(
            pl.len().alias("cnt"),
            pl.col("age").mean().alias("avg_age"),
            pl.col("weight_kg").mean().alias("avg_weight"),
            pl.col("dose").mean().alias("avg_dose"),
            pl.col("event_duration_days").median().alias("median_duration"),
            pl.col("alt_u_l").mean().alias("avg_alt"),
            pl.col("ast_u_l").mean().alias("avg_ast"),
            pl.col("bilirubin_mg_dl").mean().alias("avg_bilirubin"),
            pl.col("creatinine_mg_dl").mean().alias("avg_creatinine"),
            pl.col("bun_mg_dl").mean().alias("avg_bun")
        )
        .sort("cnt", descending=True)
        .head(50)
    ),
    "Polars: many keys + many metrics"
)
polars_complex_3

Polars: many keys + many metrics
Среднее время: 0.8684 секунд
Все замеры: [1.0782, 1.1393, 0.9312, 0.5949, 0.5984]
------------------------------------------------------------

shape: (50, 15)
┌─────────┬─────────┬───────────┬────────────┬───┬───────────┬────────────┬────────────┬───────────┐
│ country ┆ sex     ┆ age_group ┆ suspect_dr ┆ … ┆ avg_ast   ┆ avg_biliru ┆ avg_creati ┆ avg_bun   │
│ ---     ┆ ---     ┆ ---       ┆ ug         ┆   ┆ ---       ┆ bin        ┆ nine       ┆ ---       │
│ str     ┆ str     ┆ str       ┆ ---        ┆   ┆ f64       ┆ ---        ┆ ---        ┆ f64       │
│         ┆         ┆           ┆ str        ┆   ┆           ┆ f64        ┆ f64        ┆           │
╞═════════╪═════════╪═══════════╪════════════╪═══╪═══════════╪════════════╪════════════╪═══════════╡
│ ZAF     ┆ Male    ┆ adult     ┆ Psychostab ┆ … ┆ 41.090361 ┆ 1.1        ┆ 1.103247   ┆ 14.277778 │
│         ┆         ┆           ┆ il         ┆   ┆           ┆            ┆            ┆           │
│ FIN     ┆ Male    ┆ adult     ┆ Pulmofix   ┆ … ┆ 60.47561  ┆ 1.255488   ┆ 1.248428   ┆ 18.144737 │
│ CAN     ┆ Male    ┆ adult     ┆ Pulmofix   ┆ … ┆ 54.634146 ┆ 1.26131    ┆ 1.240361   ┆ 17.915663 │
│ USA     ┆ Female  ┆ adult     ┆ Dermatopin ┆ … ┆ 50.796407 ┆ 1.183436   ┆ 1.157792   ┆ 17.218935 │
│ TUR     ┆ Male    ┆ adult     ┆ Sleepwell  ┆ … ┆ 64.438272 ┆ 1.283544   ┆ 1.182927   ┆ 17.617143 │
│ …       ┆ …       ┆ …         ┆ …          ┆ … ┆ …         ┆ …          ┆ …          ┆ …         │
│ AUT     ┆ Unknown ┆ adult     ┆ Eyeprotect ┆ … ┆ 45.714286 ┆ 1.031293   ┆ 1.20068    ┆ 15.870748 │
│ IND     ┆ Male    ┆ adult     ┆ Dermatopin ┆ … ┆ 43.569536 ┆ 1.073856   ┆ 1.281884   ┆ 17.197452 │
│ POL     ┆ Female  ┆ adult     ┆ Urocare    ┆ … ┆ 53.109589 ┆ 1.279195   ┆ 1.2        ┆ 15.683453 │
│ BEL     ┆ Female  ┆ adult     ┆ Sleepwell  ┆ … ┆ 60.467105 ┆ 1.294595   ┆ 1.245638   ┆ 18.836735 │
│ GRC     ┆ Unknown ┆ adult     ┆ Glucobalan ┆ … ┆ 56.360544 ┆ 1.394631   ┆ 1.248718   ┆ 17.62987  │
│         ┆         ┆           ┆ ce         ┆   ┆           ┆            ┆            ┆           │
└─────────┴─────────┴───────────┴────────────┴───┴───────────┴────────────┴────────────┴───────────┘

In [17]:
benchmark_results = []

def benchmark_many_save(func, name, library, operation, repeats=5):
    times = []

    for _ in range(repeats):
        start = time.perf_counter()
        result = func()
        end = time.perf_counter()
        times.append(end - start)

    avg_time = sum(times) / len(times)

    benchmark_results.append({
        "library": library,
        "operation": operation,
        "avg_time_sec": round(avg_time, 4),
        "min_time_sec": round(min(times), 4),
        "max_time_sec": round(max(times), 4),
        "all_runs": [round(t, 4) for t in times]
    })

    print(f"{name}: {avg_time:.4f} секунд")
    return result

In [18]:
pandas_complex_1 = benchmark_many_save(
    lambda: (
        pdf[
            (pdf["seriousness"] == "Serious") &
            (pdf["age"].notna()) &
            (pdf["dose"].notna()) &
            (pdf["creatinine_mg_dl"].notna())
        ]
        .groupby(["suspect_drug", "outcome"])
        .agg(
            cnt=("case_id", "count"),
            avg_age=("age", "mean"),
            median_age=("age", "median"),
            avg_dose=("dose", "mean"),
            max_dose=("dose", "max"),
            avg_creatinine=("creatinine_mg_dl", "mean"),
            avg_bilirubin=("bilirubin_mg_dl", "mean")
        )
        .sort_values("cnt", ascending=False)
        .head(20)
    ),
    "Pandas complex 1",
    "Pandas",
    "complex filter + groupby"
)

polars_complex_1 = benchmark_many_save(
    lambda: (
        pldf
        .filter(
            (pl.col("seriousness") == "Serious") &
            pl.col("age").is_not_null() &
            pl.col("dose").is_not_null() &
            pl.col("creatinine_mg_dl").is_not_null()
        )
        .group_by(["suspect_drug", "outcome"])
        .agg(
            pl.len().alias("cnt"),
            pl.col("age").mean().alias("avg_age"),
            pl.col("age").median().alias("median_age"),
            pl.col("dose").mean().alias("avg_dose"),
            pl.col("dose").max().alias("max_dose"),
            pl.col("creatinine_mg_dl").mean().alias("avg_creatinine"),
            pl.col("bilirubin_mg_dl").mean().alias("avg_bilirubin")
        )
        .sort("cnt", descending=True)
        .head(20)
    ),
    "Polars complex 1",
    "Polars",
    "complex filter + groupby"
)

Pandas complex 1: 0.1023 секунд
Polars complex 1: 0.0043 секунд

In [19]:
benchmark_df = pd.DataFrame(benchmark_results)
benchmark_df

,library,operation,avg_time_sec,min_time_sec,max_time_sec,all_runs
0,Pandas,complex filter + groupby,0.1023,0.0981,0.1063,"[0.1063, 0.1027, 0.1014, 0.1032, 0.0981]"
1,Polars,complex filter + groupby,0.0043,0.0037,0.0052,"[0.0052, 0.0037, 0.0047, 0.0041, 0.0039]"

In [20]:
pandas_time = benchmark_df.loc[
    (benchmark_df["library"] == "Pandas") &
    (benchmark_df["operation"] == "complex filter + groupby"),
    "avg_time_sec"
].iloc[0]

polars_time = benchmark_df.loc[
    (benchmark_df["library"] == "Polars") &
    (benchmark_df["operation"] == "complex filter + groupby"),
    "avg_time_sec"
].iloc[0]

pandas_time / polars_time

np.float64(23.790697674418606)